### PR TITLE
Update Traditional Chinese (zh_tw.json)

### PR DESCRIPTION
**Pull request by yichifauzi**
Update Traditional Chinese to latest mod version

### CODE REVIEW

**Comment by TheCSDev** [comment]
Hello again.  
It seems commit signing is posing an issue for you. As far as I know, I think you can try uploading the translation file directly to the GitHub website for it to become signed.

**Comment by yichifauzi** [comment]
i using the github desktop to commit but my commit still not verified...

**Comment by yichifauzi** [comment]
> Hello again. It seems commit signing is posing an issue for you. As far as I know, I think you can try uploading the translation file directly to the GitHub website for it to become signed.

i will try again

**Comment by TheCSDev** [comment]
I know. This is because GitHub desktop requires you to set up a GPG key, which is a complicated process.

**Comment by TheCSDev** [comment]
If you ever wish to set up GPG, you can try looking into these articles:
- [Generating a new GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key)
- [Adding a GPG key to your GitHub account](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account)
- [Telling Git about your signing key](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key)

However this is only required if you wish to set up commit signing on GitHub Desktop and Git. If you're uploading files directly to the website however, then GitHub signs it for you.

**Pull request closed without merging**
