### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by mpustovoi**
Updated ru_ru.json via github.com

### CODE REVIEW

**Comment by mpustovoi** [comment]
Since I used my file from a previous pull request attempt, I accidentally lost the `google:gemini` in the line of translators.

**Comment by TheCSDev** [comment]
Hello again!  
Thank you so much for the updated translations and for signing the commits. I will now merge.  
Your translations will be featured in the next update, and you will be credited.  
Have a great day!

**Comment by TheCSDev** [comment]
> Since I used my file from a previous pull request attempt, I accidentally lost the `google:gemini` in the line of translators.

Also, `google:gemini` was used to translate the
```
betterstats.stattype_phrase.minecraft.killed_by
betterstats.stattype_phrase.morestats.damaged
betterstats.stattype_phrase.morestats.damaged_by
betterstats.stattype_phrase.morestats.totem_popped_by

**Comment by mpustovoi** [comment]
It also seems that it wasn't correctly transferred to the modified file.
Well, all right.

**Pull request merged**
