### PR TITLE
Update ru translation

### PR DESCRIPTION
**Pull request by Rozbiynk**

### CODE REVIEW

**Comment by Rozbiynk** [comment]
there is no config changes in 2.9.1 since 2.9?

**Review by TheCSDev — APPROVED** [review]

**Comment by Rozbiynk** [comment]
thank, but can you compile this version for me? (1.19.2)

**Comment by TheCSDev** [comment]
Sure. I'll quickly compile it as `v2.9.1` and drop it here if GitHub allows me to. It will be `v2.9.2` once it comes out.

**Comment by TheCSDev** [comment]
Here you go:
[betterstats-2.9.2+1.19.2.zip](https://github.com/TheCSMods/mc-better-stats/files/11760415/betterstats-2.9.2%2B1.19.2.zip)

I made it into `v2.9.2` anyways. Will release it publically next week tho, because like I said, don't wanna be spamming releases. Also, GitHub did not allow me to publish `.jar` here, so I made it a `.zip` you will have to extract.

**Pull request merged**
